CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"username"	TEXT UNIQUE NOT NULL,
	"salt" TEXT NOT NULL,
	"password"	TEXT NOT NULL,
	"metadata"	TEXT NOT NULL DEFAULT "{}"
);

CREATE TABLE IF NOT EXISTS "config" (
	"key"	TEXT,
	"value"	TEXT,
	PRIMARY KEY("key")
);